from typing import Dict, List, Tuple, Optional
import re
from enum import Enum


class LRPCategory:
    test = "test"
    surgery = "surgery"
    vital_signs = "vital_signs"
    medicate = "medicate"
    basic_info = "basic_info"


class ColumnMapper():
    def __init__(self, name: str, category: LRPCategory, comment: str = None, formatter: Optional[callable] = None):
        self.name = name
        self.category = category
        self.comment = comment
        self.formatter = formatter

    def format(self, data):
        if self.formatter is not None:
            return self.formatter(data)

        return data


formatters = {
    "categorical": lambda x: 'Y' if x == 1 else 'N',
    "gender": lambda x: "M" if x == 1 else "F",
}

column_mapping = {
    "p_id": ColumnMapper(name="환자번호", category=None),
    "date_admin": ColumnMapper(name="입원일", category=None),
    "date_discharge": ColumnMapper(name="퇴원일", category=None),
    "stay_length": ColumnMapper(name="입원기간", category=LRPCategory.basic_info),
    # "day": ColumnMapper(name= "입원기간", category= LRPCategory.basic_info),
    "age": ColumnMapper(name="나이", category=LRPCategory.basic_info),
    "sex": ColumnMapper(name="성별", category=LRPCategory.basic_info, formatter=formatters['gender']),
    "bmi": ColumnMapper(name="BMI", category=LRPCategory.basic_info),
    "icu": ColumnMapper(name="중환자실 입원여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "b_cr": ColumnMapper(name="baseline creatinine", category=LRPCategory.basic_info),
    "b_egfr": ColumnMapper(name="baseline egfr", category=LRPCategory.basic_info),
    "ami": ColumnMapper(name="기저질환 - AMI 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "chf": ColumnMapper(name="기저질환 - CHF 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "pvd": ColumnMapper(name="기저질환 - PVD 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "cvd": ColumnMapper(name="기저질환 - CVD 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "dementia": ColumnMapper(name="기저질환 - DEMENTIA 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "pulmonary_disease": ColumnMapper(name="기저질환 - PULMONARY DISEASE 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "ctd": ColumnMapper(name="기저질환 - CTD 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "peptic_ulcer": ColumnMapper(name="기저질환 - PEPTIC ULCER 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "liver_disease": ColumnMapper(name="기저질환 - LIVER DISEASE 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "severe_liver_disease": ColumnMapper(name="기저질환 - SEVERE_LIVER_DISEASE 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "diabetes": ColumnMapper(name="기저질환 - DIABETES 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "diabetic_complication": ColumnMapper(name="기저질환 - DIABETIC COMPLICATION 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "paraplegia": ColumnMapper(name="기저질환 - PARAPLEGIA 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "renal_disease": ColumnMapper(name="기저질환 - RENAL DISEASE 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "cancer": ColumnMapper(name="기저질환 - CANCER 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "metastatic_cancer": ColumnMapper(name="기저질환 - METASTATIC CANCER 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "hiv": ColumnMapper(name="기저질환 - HIV 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "htn": ColumnMapper(name="기저질환 - HTN 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "aki": ColumnMapper(name="기저질환 - AKI 여부", category=LRPCategory.basic_info, formatter=formatters['categorical']),
    "cci": ColumnMapper(name="Charlson Comorbidity Index 계산값", category=LRPCategory.basic_info),
    "pre6m_acei": ColumnMapper(name="입원 전 6개월 이내 ACEI 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_acyclovir": ColumnMapper(name="입원 전 6개월 이내 ACYCLOVIR 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_aminoglycoside": ColumnMapper(name="입원 전 6개월 이내 AMINOGLYCOSIDE 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_amphotericin": ColumnMapper(name="입원 전 6개월 이내 AMPHOTERICIN 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_arb": ColumnMapper(name="입원 전 6개월 이내 ARB 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_betablocker": ColumnMapper(name="입원 전 6개월 이내 BETABLOCKER 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_ccb": ColumnMapper(name="입원 전 6개월 이내 CCB 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_cisplatin": ColumnMapper(name="입원 전 6개월 이내 CISPLATIN 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_colistin": ColumnMapper(name="입원 전 6개월 이내 COLISTIN 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_cyclosporin": ColumnMapper(name="입원 전 6개월 이내 CYCLOSPORIN 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_diuretics": ColumnMapper(name="입원 전 6개월 이내 DIURETICS 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_nsaid": ColumnMapper(name="입원 전 6개월 이내 NSAIDs 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_statin": ColumnMapper(name="입원 전 6개월 이내 STATIN 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_tacrolimus": ColumnMapper(name="입원 전 6개월 이내 TACROLIMUS 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_vancomycin": ColumnMapper(name="입원 전 6개월 이내 VANCOMYCIN 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "pre6m_vasopressor": ColumnMapper(name="입원 전 6개월 이내 VASOPRESSOR 처방 여부", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d2_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d3_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d4_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d5_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d6_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_acei": ColumnMapper(name="ACEI 처방 여부", comment="ACEi가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_acyclovir": ColumnMapper(name="ACYCLOVIR 처방 여부", comment="Acyclovir가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_aminoglycoside": ColumnMapper(name="AMINOGLYCOSIDE 처방 여부", comment="Aminoglycoside가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_amphotericin": ColumnMapper(name="AMPHOTERICIN 처방 여부", comment="Amphotericin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_arb": ColumnMapper(name="ARB 처방 여부", comment="ARB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_betablocker": ColumnMapper(name="BETABLOCKER 처방 여부", comment="Beta blocker가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_ccb": ColumnMapper(name="CCB 처방 여부", comment="CCB가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_cisplatin": ColumnMapper(name="CISPLATIN 처방 여부", comment="Cisplatin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_colistin": ColumnMapper(name="COLISTIN 처방 여부", comment="Colistin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_cyclosporin": ColumnMapper(name="CYCLOSPORIN 처방 여부", comment="Cyclosporin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_diuretics": ColumnMapper(name="DIURETICS 처방 여부", comment="Diuretics가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_nsaid": ColumnMapper(name="NSAIDs 처방 여부", comment="NSAIDs가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_statin": ColumnMapper(name="STATIN 처방 여부", comment="Statin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_tacrolimus": ColumnMapper(name="TACROLIMUS 처방 여부", comment="Tacrolimus가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 다른약제와 상호작용에 주의하시길 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_vancomycin": ColumnMapper(name="VANCOMYCIN 처방 여부", comment="Vacomycin이 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다. 사구체여과율 확인 후 용량 조절 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d7_vasopressor": ColumnMapper(name="VASOPRESSOR 처방 여부", comment="Vasopressor가 급성신손상의 원인일 가능성이 있다면 감량 혹은 중단 고려 바랍니다.", category=LRPCategory.medicate, formatter=formatters['categorical']),
    "d1_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d1_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d1_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d1_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d1_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d2_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d2_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d2_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d2_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d2_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d3_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d3_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d3_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d3_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d3_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d4_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d4_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d4_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d4_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d4_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d5_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d5_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d5_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d5_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d5_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d6_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d6_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d6_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d6_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d6_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d7_op_major": ColumnMapper(name="major 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d7_op_minor": ColumnMapper(name="minor 수술 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d7_anes_general": ColumnMapper(name="전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d7_anes_non_general": ColumnMapper(name="비전신마취 여부", category=LRPCategory.surgery, formatter=formatters['categorical']),
    "d7_surgery_time": ColumnMapper(name="수술시간(분)", category=LRPCategory.surgery),
    "d1_1_albumin": ColumnMapper(name="입원  1일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d1_2_albumin": ColumnMapper(name="입원  1일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d1_3_albumin": ColumnMapper(name="입원  1일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d2_1_albumin": ColumnMapper(name="입원  2일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d2_2_albumin": ColumnMapper(name="입원  2일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d2_3_albumin": ColumnMapper(name="입원  2일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d3_1_albumin": ColumnMapper(name="입원  3일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d3_2_albumin": ColumnMapper(name="입원  3일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d3_3_albumin": ColumnMapper(name="입원  3일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d4_1_albumin": ColumnMapper(name="입원  4일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d4_2_albumin": ColumnMapper(name="입원  4일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d4_3_albumin": ColumnMapper(name="입원  4일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d5_1_albumin": ColumnMapper(name="입원  5일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d5_2_albumin": ColumnMapper(name="입원  5일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d5_3_albumin": ColumnMapper(name="입원  5일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d6_1_albumin": ColumnMapper(name="입원  6일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d6_2_albumin": ColumnMapper(name="입원  6일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d6_3_albumin": ColumnMapper(name="입원  6일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d7_1_albumin": ColumnMapper(name="입원  7일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d7_2_albumin": ColumnMapper(name="입원  7일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d7_3_albumin": ColumnMapper(name="입원  7일 ALBUMIN 검사결과 평균", category=LRPCategory.test),
    "d1_1_bilirubin": ColumnMapper(name="입원  1일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d1_2_bilirubin": ColumnMapper(name="입원  1일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d1_3_bilirubin": ColumnMapper(name="입원  1일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d2_1_bilirubin": ColumnMapper(name="입원  2일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d2_2_bilirubin": ColumnMapper(name="입원  2일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d2_3_bilirubin": ColumnMapper(name="입원  2일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d3_1_bilirubin": ColumnMapper(name="입원  3일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d3_2_bilirubin": ColumnMapper(name="입원  3일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d3_3_bilirubin": ColumnMapper(name="입원  3일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d4_1_bilirubin": ColumnMapper(name="입원  4일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d4_2_bilirubin": ColumnMapper(name="입원  4일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d4_3_bilirubin": ColumnMapper(name="입원  4일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d5_1_bilirubin": ColumnMapper(name="입원  5일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d5_2_bilirubin": ColumnMapper(name="입원  5일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d5_3_bilirubin": ColumnMapper(name="입원  5일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d6_1_bilirubin": ColumnMapper(name="입원  6일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d6_2_bilirubin": ColumnMapper(name="입원  6일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d6_3_bilirubin": ColumnMapper(name="입원  6일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d7_1_bilirubin": ColumnMapper(name="입원  7일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d7_2_bilirubin": ColumnMapper(name="입원  7일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d7_3_bilirubin": ColumnMapper(name="입원  7일 BILIRUBIN 검사결과 평균", category=LRPCategory.test),
    "d1_1_bun": ColumnMapper(name="입원  1일 BUN 검사결과 평균", category=LRPCategory.test),
    "d1_2_bun": ColumnMapper(name="입원  1일 BUN 검사결과 평균", category=LRPCategory.test),
    "d1_3_bun": ColumnMapper(name="입원  1일 BUN 검사결과 평균", category=LRPCategory.test),
    "d2_1_bun": ColumnMapper(name="입원  2일 BUN 검사결과 평균", category=LRPCategory.test),
    "d2_2_bun": ColumnMapper(name="입원  2일 BUN 검사결과 평균", category=LRPCategory.test),
    "d2_3_bun": ColumnMapper(name="입원  2일 BUN 검사결과 평균", category=LRPCategory.test),
    "d3_1_bun": ColumnMapper(name="입원  3일 BUN 검사결과 평균", category=LRPCategory.test),
    "d3_2_bun": ColumnMapper(name="입원  3일 BUN 검사결과 평균", category=LRPCategory.test),
    "d3_3_bun": ColumnMapper(name="입원  3일 BUN 검사결과 평균", category=LRPCategory.test),
    "d4_1_bun": ColumnMapper(name="입원  4일 BUN 검사결과 평균", category=LRPCategory.test),
    "d4_2_bun": ColumnMapper(name="입원  4일 BUN 검사결과 평균", category=LRPCategory.test),
    "d4_3_bun": ColumnMapper(name="입원  4일 BUN 검사결과 평균", category=LRPCategory.test),
    "d5_1_bun": ColumnMapper(name="입원  5일 BUN 검사결과 평균", category=LRPCategory.test),
    "d5_2_bun": ColumnMapper(name="입원  5일 BUN 검사결과 평균", category=LRPCategory.test),
    "d5_3_bun": ColumnMapper(name="입원  5일 BUN 검사결과 평균", category=LRPCategory.test),
    "d6_1_bun": ColumnMapper(name="입원  6일 BUN 검사결과 평균", category=LRPCategory.test),
    "d6_2_bun": ColumnMapper(name="입원  6일 BUN 검사결과 평균", category=LRPCategory.test),
    "d6_3_bun": ColumnMapper(name="입원  6일 BUN 검사결과 평균", category=LRPCategory.test),
    "d7_1_bun": ColumnMapper(name="입원  7일 BUN 검사결과 평균", category=LRPCategory.test),
    "d7_2_bun": ColumnMapper(name="입원  7일 BUN 검사결과 평균", category=LRPCategory.test),
    "d7_3_bun": ColumnMapper(name="입원  7일 BUN 검사결과 평균", category=LRPCategory.test),
    "d1_1_calcium": ColumnMapper(name="입원  1일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d1_2_calcium": ColumnMapper(name="입원  1일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d1_3_calcium": ColumnMapper(name="입원  1일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d2_1_calcium": ColumnMapper(name="입원  2일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d2_2_calcium": ColumnMapper(name="입원  2일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d2_3_calcium": ColumnMapper(name="입원  2일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d3_1_calcium": ColumnMapper(name="입원  3일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d3_2_calcium": ColumnMapper(name="입원  3일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d3_3_calcium": ColumnMapper(name="입원  3일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d4_1_calcium": ColumnMapper(name="입원  4일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d4_2_calcium": ColumnMapper(name="입원  4일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d4_3_calcium": ColumnMapper(name="입원  4일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d5_1_calcium": ColumnMapper(name="입원  5일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d5_2_calcium": ColumnMapper(name="입원  5일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d5_3_calcium": ColumnMapper(name="입원  5일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d6_1_calcium": ColumnMapper(name="입원  6일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d6_2_calcium": ColumnMapper(name="입원  6일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d6_3_calcium": ColumnMapper(name="입원  6일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d7_1_calcium": ColumnMapper(name="입원  7일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d7_2_calcium": ColumnMapper(name="입원  7일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d7_3_calcium": ColumnMapper(name="입원  7일 CALCIUM 검사결과 평균", category=LRPCategory.test),
    "d1_1_chloride": ColumnMapper(name="입원  1일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d1_2_chloride": ColumnMapper(name="입원  1일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d1_3_chloride": ColumnMapper(name="입원  1일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d2_1_chloride": ColumnMapper(name="입원  2일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d2_2_chloride": ColumnMapper(name="입원  2일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d2_3_chloride": ColumnMapper(name="입원  2일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d3_1_chloride": ColumnMapper(name="입원  3일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d3_2_chloride": ColumnMapper(name="입원  3일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d3_3_chloride": ColumnMapper(name="입원  3일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d4_1_chloride": ColumnMapper(name="입원  4일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d4_2_chloride": ColumnMapper(name="입원  4일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d4_3_chloride": ColumnMapper(name="입원  4일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d5_1_chloride": ColumnMapper(name="입원  5일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d5_2_chloride": ColumnMapper(name="입원  5일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d5_3_chloride": ColumnMapper(name="입원  5일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d6_1_chloride": ColumnMapper(name="입원  6일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d6_2_chloride": ColumnMapper(name="입원  6일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d6_3_chloride": ColumnMapper(name="입원  6일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d7_1_chloride": ColumnMapper(name="입원  7일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d7_2_chloride": ColumnMapper(name="입원  7일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d7_3_chloride": ColumnMapper(name="입원  7일 CHLORIDE 검사결과 평균", category=LRPCategory.test),
    "d1_1_ck": ColumnMapper(name="입원  1일 CK 검사결과 평균", category=LRPCategory.test),
    "d1_2_ck": ColumnMapper(name="입원  1일 CK 검사결과 평균", category=LRPCategory.test),
    "d1_3_ck": ColumnMapper(name="입원  1일 CK 검사결과 평균", category=LRPCategory.test),
    "d2_1_ck": ColumnMapper(name="입원  2일 CK 검사결과 평균", category=LRPCategory.test),
    "d2_2_ck": ColumnMapper(name="입원  2일 CK 검사결과 평균", category=LRPCategory.test),
    "d2_3_ck": ColumnMapper(name="입원  2일 CK 검사결과 평균", category=LRPCategory.test),
    "d3_1_ck": ColumnMapper(name="입원  3일 CK 검사결과 평균", category=LRPCategory.test),
    "d3_2_ck": ColumnMapper(name="입원  3일 CK 검사결과 평균", category=LRPCategory.test),
    "d3_3_ck": ColumnMapper(name="입원  3일 CK 검사결과 평균", category=LRPCategory.test),
    "d4_1_ck": ColumnMapper(name="입원  4일 CK 검사결과 평균", category=LRPCategory.test),
    "d4_2_ck": ColumnMapper(name="입원  4일 CK 검사결과 평균", category=LRPCategory.test),
    "d4_3_ck": ColumnMapper(name="입원  4일 CK 검사결과 평균", category=LRPCategory.test),
    "d5_1_ck": ColumnMapper(name="입원  5일 CK 검사결과 평균", category=LRPCategory.test),
    "d5_2_ck": ColumnMapper(name="입원  5일 CK 검사결과 평균", category=LRPCategory.test),
    "d5_3_ck": ColumnMapper(name="입원  5일 CK 검사결과 평균", category=LRPCategory.test),
    "d6_1_ck": ColumnMapper(name="입원  6일 CK 검사결과 평균", category=LRPCategory.test),
    "d6_2_ck": ColumnMapper(name="입원  6일 CK 검사결과 평균", category=LRPCategory.test),
    "d6_3_ck": ColumnMapper(name="입원  6일 CK 검사결과 평균", category=LRPCategory.test),
    "d7_1_ck": ColumnMapper(name="입원  7일 CK 검사결과 평균", category=LRPCategory.test),
    "d7_2_ck": ColumnMapper(name="입원  7일 CK 검사결과 평균", category=LRPCategory.test),
    "d7_3_ck": ColumnMapper(name="입원  7일 CK 검사결과 평균", category=LRPCategory.test),
    "d1_1_co2": ColumnMapper(name="입원  1일 CO2 검사결과 평균", category=LRPCategory.test),
    "d1_2_co2": ColumnMapper(name="입원  1일 CO2 검사결과 평균", category=LRPCategory.test),
    "d1_3_co2": ColumnMapper(name="입원  1일 CO2 검사결과 평균", category=LRPCategory.test),
    "d2_1_co2": ColumnMapper(name="입원  2일 CO2 검사결과 평균", category=LRPCategory.test),
    "d2_2_co2": ColumnMapper(name="입원  2일 CO2 검사결과 평균", category=LRPCategory.test),
    "d2_3_co2": ColumnMapper(name="입원  2일 CO2 검사결과 평균", category=LRPCategory.test),
    "d3_1_co2": ColumnMapper(name="입원  3일 CO2 검사결과 평균", category=LRPCategory.test),
    "d3_2_co2": ColumnMapper(name="입원  3일 CO2 검사결과 평균", category=LRPCategory.test),
    "d3_3_co2": ColumnMapper(name="입원  3일 CO2 검사결과 평균", category=LRPCategory.test),
    "d4_1_co2": ColumnMapper(name="입원  4일 CO2 검사결과 평균", category=LRPCategory.test),
    "d4_2_co2": ColumnMapper(name="입원  4일 CO2 검사결과 평균", category=LRPCategory.test),
    "d4_3_co2": ColumnMapper(name="입원  4일 CO2 검사결과 평균", category=LRPCategory.test),
    "d5_1_co2": ColumnMapper(name="입원  5일 CO2 검사결과 평균", category=LRPCategory.test),
    "d5_2_co2": ColumnMapper(name="입원  5일 CO2 검사결과 평균", category=LRPCategory.test),
    "d5_3_co2": ColumnMapper(name="입원  5일 CO2 검사결과 평균", category=LRPCategory.test),
    "d6_1_co2": ColumnMapper(name="입원  6일 CO2 검사결과 평균", category=LRPCategory.test),
    "d6_2_co2": ColumnMapper(name="입원  6일 CO2 검사결과 평균", category=LRPCategory.test),
    "d6_3_co2": ColumnMapper(name="입원  6일 CO2 검사결과 평균", category=LRPCategory.test),
    "d7_1_co2": ColumnMapper(name="입원  7일 CO2 검사결과 평균", category=LRPCategory.test),
    "d7_2_co2": ColumnMapper(name="입원  7일 CO2 검사결과 평균", category=LRPCategory.test),
    "d7_3_co2": ColumnMapper(name="입원  7일 CO2 검사결과 평균", category=LRPCategory.test),
    "d1_1_creatinine": ColumnMapper(name="입원  1일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d1_2_creatinine": ColumnMapper(name="입원  1일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d1_3_creatinine": ColumnMapper(name="입원  1일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d2_1_creatinine": ColumnMapper(name="입원  2일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d2_2_creatinine": ColumnMapper(name="입원  2일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d2_3_creatinine": ColumnMapper(name="입원  2일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d3_1_creatinine": ColumnMapper(name="입원  3일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d3_2_creatinine": ColumnMapper(name="입원  3일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d3_3_creatinine": ColumnMapper(name="입원  3일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d4_1_creatinine": ColumnMapper(name="입원  4일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d4_2_creatinine": ColumnMapper(name="입원  4일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d4_3_creatinine": ColumnMapper(name="입원  4일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d5_1_creatinine": ColumnMapper(name="입원  5일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d5_2_creatinine": ColumnMapper(name="입원  5일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d5_3_creatinine": ColumnMapper(name="입원  5일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d6_1_creatinine": ColumnMapper(name="입원  6일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d6_2_creatinine": ColumnMapper(name="입원  6일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d6_3_creatinine": ColumnMapper(name="입원  6일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d7_1_creatinine": ColumnMapper(name="입원  7일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d7_2_creatinine": ColumnMapper(name="입원  7일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d7_3_creatinine": ColumnMapper(name="입원  7일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d8_1_creatinine": ColumnMapper(name="입원  8일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d8_2_creatinine": ColumnMapper(name="입원  8일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d8_3_creatinine": ColumnMapper(name="입원  8일 CREATININE 검사결과 평균", category=LRPCategory.test),
    "d1_1_crp": ColumnMapper(name="입원  1일 CRP 검사결과 평균", category=LRPCategory.test),
    "d1_2_crp": ColumnMapper(name="입원  1일 CRP 검사결과 평균", category=LRPCategory.test),
    "d1_3_crp": ColumnMapper(name="입원  1일 CRP 검사결과 평균", category=LRPCategory.test),
    "d2_1_crp": ColumnMapper(name="입원  2일 CRP 검사결과 평균", category=LRPCategory.test),
    "d2_2_crp": ColumnMapper(name="입원  2일 CRP 검사결과 평균", category=LRPCategory.test),
    "d2_3_crp": ColumnMapper(name="입원  2일 CRP 검사결과 평균", category=LRPCategory.test),
    "d3_1_crp": ColumnMapper(name="입원  3일 CRP 검사결과 평균", category=LRPCategory.test),
    "d3_2_crp": ColumnMapper(name="입원  3일 CRP 검사결과 평균", category=LRPCategory.test),
    "d3_3_crp": ColumnMapper(name="입원  3일 CRP 검사결과 평균", category=LRPCategory.test),
    "d4_1_crp": ColumnMapper(name="입원  4일 CRP 검사결과 평균", category=LRPCategory.test),
    "d4_2_crp": ColumnMapper(name="입원  4일 CRP 검사결과 평균", category=LRPCategory.test),
    "d4_3_crp": ColumnMapper(name="입원  4일 CRP 검사결과 평균", category=LRPCategory.test),
    "d5_1_crp": ColumnMapper(name="입원  5일 CRP 검사결과 평균", category=LRPCategory.test),
    "d5_2_crp": ColumnMapper(name="입원  5일 CRP 검사결과 평균", category=LRPCategory.test),
    "d5_3_crp": ColumnMapper(name="입원  5일 CRP 검사결과 평균", category=LRPCategory.test),
    "d6_1_crp": ColumnMapper(name="입원  6일 CRP 검사결과 평균", category=LRPCategory.test),
    "d6_2_crp": ColumnMapper(name="입원  6일 CRP 검사결과 평균", category=LRPCategory.test),
    "d6_3_crp": ColumnMapper(name="입원  6일 CRP 검사결과 평균", category=LRPCategory.test),
    "d7_1_crp": ColumnMapper(name="입원  7일 CRP 검사결과 평균", category=LRPCategory.test),
    "d7_2_crp": ColumnMapper(name="입원  7일 CRP 검사결과 평균", category=LRPCategory.test),
    "d7_3_crp": ColumnMapper(name="입원  7일 CRP 검사결과 평균", category=LRPCategory.test),
    "d1_1_glucose": ColumnMapper(name="입원  1일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d1_2_glucose": ColumnMapper(name="입원  1일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d1_3_glucose": ColumnMapper(name="입원  1일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d2_1_glucose": ColumnMapper(name="입원  2일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d2_2_glucose": ColumnMapper(name="입원  2일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d2_3_glucose": ColumnMapper(name="입원  2일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d3_1_glucose": ColumnMapper(name="입원  3일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d3_2_glucose": ColumnMapper(name="입원  3일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d3_3_glucose": ColumnMapper(name="입원  3일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d4_1_glucose": ColumnMapper(name="입원  4일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d4_2_glucose": ColumnMapper(name="입원  4일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d4_3_glucose": ColumnMapper(name="입원  4일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d5_1_glucose": ColumnMapper(name="입원  5일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d5_2_glucose": ColumnMapper(name="입원  5일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d5_3_glucose": ColumnMapper(name="입원  5일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d6_1_glucose": ColumnMapper(name="입원  6일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d6_2_glucose": ColumnMapper(name="입원  6일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d6_3_glucose": ColumnMapper(name="입원  6일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d7_1_glucose": ColumnMapper(name="입원  7일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d7_2_glucose": ColumnMapper(name="입원  7일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d7_3_glucose": ColumnMapper(name="입원  7일 GLUCOSE 검사결과 평균", category=LRPCategory.test),
    "d1_1_got": ColumnMapper(name="입원  1일 GOT 검사결과 평균", category=LRPCategory.test),
    "d1_2_got": ColumnMapper(name="입원  1일 GOT 검사결과 평균", category=LRPCategory.test),
    "d1_3_got": ColumnMapper(name="입원  1일 GOT 검사결과 평균", category=LRPCategory.test),
    "d2_1_got": ColumnMapper(name="입원  2일 GOT 검사결과 평균", category=LRPCategory.test),
    "d2_2_got": ColumnMapper(name="입원  2일 GOT 검사결과 평균", category=LRPCategory.test),
    "d2_3_got": ColumnMapper(name="입원  2일 GOT 검사결과 평균", category=LRPCategory.test),
    "d3_1_got": ColumnMapper(name="입원  3일 GOT 검사결과 평균", category=LRPCategory.test),
    "d3_2_got": ColumnMapper(name="입원  3일 GOT 검사결과 평균", category=LRPCategory.test),
    "d3_3_got": ColumnMapper(name="입원  3일 GOT 검사결과 평균", category=LRPCategory.test),
    "d4_1_got": ColumnMapper(name="입원  4일 GOT 검사결과 평균", category=LRPCategory.test),
    "d4_2_got": ColumnMapper(name="입원  4일 GOT 검사결과 평균", category=LRPCategory.test),
    "d4_3_got": ColumnMapper(name="입원  4일 GOT 검사결과 평균", category=LRPCategory.test),
    "d5_1_got": ColumnMapper(name="입원  5일 GOT 검사결과 평균", category=LRPCategory.test),
    "d5_2_got": ColumnMapper(name="입원  5일 GOT 검사결과 평균", category=LRPCategory.test),
    "d5_3_got": ColumnMapper(name="입원  5일 GOT 검사결과 평균", category=LRPCategory.test),
    "d6_1_got": ColumnMapper(name="입원  6일 GOT 검사결과 평균", category=LRPCategory.test),
    "d6_2_got": ColumnMapper(name="입원  6일 GOT 검사결과 평균", category=LRPCategory.test),
    "d6_3_got": ColumnMapper(name="입원  6일 GOT 검사결과 평균", category=LRPCategory.test),
    "d7_1_got": ColumnMapper(name="입원  7일 GOT 검사결과 평균", category=LRPCategory.test),
    "d7_2_got": ColumnMapper(name="입원  7일 GOT 검사결과 평균", category=LRPCategory.test),
    "d7_3_got": ColumnMapper(name="입원  7일 GOT 검사결과 평균", category=LRPCategory.test),
    "d1_1_gpt": ColumnMapper(name="입원  1일 GPT 검사결과 평균", category=LRPCategory.test),
    "d1_2_gpt": ColumnMapper(name="입원  1일 GPT 검사결과 평균", category=LRPCategory.test),
    "d1_3_gpt": ColumnMapper(name="입원  1일 GPT 검사결과 평균", category=LRPCategory.test),
    "d2_1_gpt": ColumnMapper(name="입원  2일 GPT 검사결과 평균", category=LRPCategory.test),
    "d2_2_gpt": ColumnMapper(name="입원  2일 GPT 검사결과 평균", category=LRPCategory.test),
    "d2_3_gpt": ColumnMapper(name="입원  2일 GPT 검사결과 평균", category=LRPCategory.test),
    "d3_1_gpt": ColumnMapper(name="입원  3일 GPT 검사결과 평균", category=LRPCategory.test),
    "d3_2_gpt": ColumnMapper(name="입원  3일 GPT 검사결과 평균", category=LRPCategory.test),
    "d3_3_gpt": ColumnMapper(name="입원  3일 GPT 검사결과 평균", category=LRPCategory.test),
    "d4_1_gpt": ColumnMapper(name="입원  4일 GPT 검사결과 평균", category=LRPCategory.test),
    "d4_2_gpt": ColumnMapper(name="입원  4일 GPT 검사결과 평균", category=LRPCategory.test),
    "d4_3_gpt": ColumnMapper(name="입원  4일 GPT 검사결과 평균", category=LRPCategory.test),
    "d5_1_gpt": ColumnMapper(name="입원  5일 GPT 검사결과 평균", category=LRPCategory.test),
    "d5_2_gpt": ColumnMapper(name="입원  5일 GPT 검사결과 평균", category=LRPCategory.test),
    "d5_3_gpt": ColumnMapper(name="입원  5일 GPT 검사결과 평균", category=LRPCategory.test),
    "d6_1_gpt": ColumnMapper(name="입원  6일 GPT 검사결과 평균", category=LRPCategory.test),
    "d6_2_gpt": ColumnMapper(name="입원  6일 GPT 검사결과 평균", category=LRPCategory.test),
    "d6_3_gpt": ColumnMapper(name="입원  6일 GPT 검사결과 평균", category=LRPCategory.test),
    "d7_1_gpt": ColumnMapper(name="입원  7일 GPT 검사결과 평균", category=LRPCategory.test),
    "d7_2_gpt": ColumnMapper(name="입원  7일 GPT 검사결과 평균", category=LRPCategory.test),
    "d7_3_gpt": ColumnMapper(name="입원  7일 GPT 검사결과 평균", category=LRPCategory.test),
    "d1_1_hb": ColumnMapper(name="입원  1일 HB 검사결과 평균", category=LRPCategory.test),
    "d1_2_hb": ColumnMapper(name="입원  1일 HB 검사결과 평균", category=LRPCategory.test),
    "d1_3_hb": ColumnMapper(name="입원  1일 HB 검사결과 평균", category=LRPCategory.test),
    "d2_1_hb": ColumnMapper(name="입원  2일 HB 검사결과 평균", category=LRPCategory.test),
    "d2_2_hb": ColumnMapper(name="입원  2일 HB 검사결과 평균", category=LRPCategory.test),
    "d2_3_hb": ColumnMapper(name="입원  2일 HB 검사결과 평균", category=LRPCategory.test),
    "d3_1_hb": ColumnMapper(name="입원  3일 HB 검사결과 평균", category=LRPCategory.test),
    "d3_2_hb": ColumnMapper(name="입원  3일 HB 검사결과 평균", category=LRPCategory.test),
    "d3_3_hb": ColumnMapper(name="입원  3일 HB 검사결과 평균", category=LRPCategory.test),
    "d4_1_hb": ColumnMapper(name="입원  4일 HB 검사결과 평균", category=LRPCategory.test),
    "d4_2_hb": ColumnMapper(name="입원  4일 HB 검사결과 평균", category=LRPCategory.test),
    "d4_3_hb": ColumnMapper(name="입원  4일 HB 검사결과 평균", category=LRPCategory.test),
    "d5_1_hb": ColumnMapper(name="입원  5일 HB 검사결과 평균", category=LRPCategory.test),
    "d5_2_hb": ColumnMapper(name="입원  5일 HB 검사결과 평균", category=LRPCategory.test),
    "d5_3_hb": ColumnMapper(name="입원  5일 HB 검사결과 평균", category=LRPCategory.test),
    "d6_1_hb": ColumnMapper(name="입원  6일 HB 검사결과 평균", category=LRPCategory.test),
    "d6_2_hb": ColumnMapper(name="입원  6일 HB 검사결과 평균", category=LRPCategory.test),
    "d6_3_hb": ColumnMapper(name="입원  6일 HB 검사결과 평균", category=LRPCategory.test),
    "d7_1_hb": ColumnMapper(name="입원  7일 HB 검사결과 평균", category=LRPCategory.test),
    "d7_2_hb": ColumnMapper(name="입원  7일 HB 검사결과 평균", category=LRPCategory.test),
    "d7_3_hb": ColumnMapper(name="입원  7일 HB 검사결과 평균", category=LRPCategory.test),
    "d1_1_lipase": ColumnMapper(name="입원  1일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d1_2_lipase": ColumnMapper(name="입원  1일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d1_3_lipase": ColumnMapper(name="입원  1일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d2_1_lipase": ColumnMapper(name="입원  2일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d2_2_lipase": ColumnMapper(name="입원  2일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d2_3_lipase": ColumnMapper(name="입원  2일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d3_1_lipase": ColumnMapper(name="입원  3일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d3_2_lipase": ColumnMapper(name="입원  3일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d3_3_lipase": ColumnMapper(name="입원  3일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d4_1_lipase": ColumnMapper(name="입원  4일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d4_2_lipase": ColumnMapper(name="입원  4일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d4_3_lipase": ColumnMapper(name="입원  4일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d5_1_lipase": ColumnMapper(name="입원  5일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d5_2_lipase": ColumnMapper(name="입원  5일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d5_3_lipase": ColumnMapper(name="입원  5일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d6_1_lipase": ColumnMapper(name="입원  6일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d6_2_lipase": ColumnMapper(name="입원  6일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d6_3_lipase": ColumnMapper(name="입원  6일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d7_1_lipase": ColumnMapper(name="입원  7일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d7_2_lipase": ColumnMapper(name="입원  7일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d7_3_lipase": ColumnMapper(name="입원  7일 LIPASE 검사결과 평균", category=LRPCategory.test),
    "d1_1_plt": ColumnMapper(name="입원  1일 PLT 검사결과 평균", category=LRPCategory.test),
    "d1_2_plt": ColumnMapper(name="입원  1일 PLT 검사결과 평균", category=LRPCategory.test),
    "d1_3_plt": ColumnMapper(name="입원  1일 PLT 검사결과 평균", category=LRPCategory.test),
    "d2_1_plt": ColumnMapper(name="입원  2일 PLT 검사결과 평균", category=LRPCategory.test),
    "d2_2_plt": ColumnMapper(name="입원  2일 PLT 검사결과 평균", category=LRPCategory.test),
    "d2_3_plt": ColumnMapper(name="입원  2일 PLT 검사결과 평균", category=LRPCategory.test),
    "d3_1_plt": ColumnMapper(name="입원  3일 PLT 검사결과 평균", category=LRPCategory.test),
    "d3_2_plt": ColumnMapper(name="입원  3일 PLT 검사결과 평균", category=LRPCategory.test),
    "d3_3_plt": ColumnMapper(name="입원  3일 PLT 검사결과 평균", category=LRPCategory.test),
    "d4_1_plt": ColumnMapper(name="입원  4일 PLT 검사결과 평균", category=LRPCategory.test),
    "d4_2_plt": ColumnMapper(name="입원  4일 PLT 검사결과 평균", category=LRPCategory.test),
    "d4_3_plt": ColumnMapper(name="입원  4일 PLT 검사결과 평균", category=LRPCategory.test),
    "d5_1_plt": ColumnMapper(name="입원  5일 PLT 검사결과 평균", category=LRPCategory.test),
    "d5_2_plt": ColumnMapper(name="입원  5일 PLT 검사결과 평균", category=LRPCategory.test),
    "d5_3_plt": ColumnMapper(name="입원  5일 PLT 검사결과 평균", category=LRPCategory.test),
    "d6_1_plt": ColumnMapper(name="입원  6일 PLT 검사결과 평균", category=LRPCategory.test),
    "d6_2_plt": ColumnMapper(name="입원  6일 PLT 검사결과 평균", category=LRPCategory.test),
    "d6_3_plt": ColumnMapper(name="입원  6일 PLT 검사결과 평균", category=LRPCategory.test),
    "d7_1_plt": ColumnMapper(name="입원  7일 PLT 검사결과 평균", category=LRPCategory.test),
    "d7_2_plt": ColumnMapper(name="입원  7일 PLT 검사결과 평균", category=LRPCategory.test),
    "d7_3_plt": ColumnMapper(name="입원  7일 PLT 검사결과 평균", category=LRPCategory.test),
    "d1_1_potassium": ColumnMapper(name="입원  1일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d1_2_potassium": ColumnMapper(name="입원  1일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d1_3_potassium": ColumnMapper(name="입원  1일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d2_1_potassium": ColumnMapper(name="입원  2일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d2_2_potassium": ColumnMapper(name="입원  2일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d2_3_potassium": ColumnMapper(name="입원  2일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d3_1_potassium": ColumnMapper(name="입원  3일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d3_2_potassium": ColumnMapper(name="입원  3일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d3_3_potassium": ColumnMapper(name="입원  3일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d4_1_potassium": ColumnMapper(name="입원  4일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d4_2_potassium": ColumnMapper(name="입원  4일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d4_3_potassium": ColumnMapper(name="입원  4일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d5_1_potassium": ColumnMapper(name="입원  5일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d5_2_potassium": ColumnMapper(name="입원  5일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d5_3_potassium": ColumnMapper(name="입원  5일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d6_1_potassium": ColumnMapper(name="입원  6일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d6_2_potassium": ColumnMapper(name="입원  6일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d6_3_potassium": ColumnMapper(name="입원  6일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d7_1_potassium": ColumnMapper(name="입원  7일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d7_2_potassium": ColumnMapper(name="입원  7일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d7_3_potassium": ColumnMapper(name="입원  7일 POTASSIUM 검사결과 평균", category=LRPCategory.test),
    "d1_1_sodium": ColumnMapper(name="입원  1일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d1_2_sodium": ColumnMapper(name="입원  1일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d1_3_sodium": ColumnMapper(name="입원  1일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d2_1_sodium": ColumnMapper(name="입원  2일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d2_2_sodium": ColumnMapper(name="입원  2일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d2_3_sodium": ColumnMapper(name="입원  2일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d3_1_sodium": ColumnMapper(name="입원  3일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d3_2_sodium": ColumnMapper(name="입원  3일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d3_3_sodium": ColumnMapper(name="입원  3일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d4_1_sodium": ColumnMapper(name="입원  4일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d4_2_sodium": ColumnMapper(name="입원  4일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d4_3_sodium": ColumnMapper(name="입원  4일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d5_1_sodium": ColumnMapper(name="입원  5일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d5_2_sodium": ColumnMapper(name="입원  5일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d5_3_sodium": ColumnMapper(name="입원  5일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d6_1_sodium": ColumnMapper(name="입원  6일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d6_2_sodium": ColumnMapper(name="입원  6일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d6_3_sodium": ColumnMapper(name="입원  6일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d7_1_sodium": ColumnMapper(name="입원  7일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d7_2_sodium": ColumnMapper(name="입원  7일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d7_3_sodium": ColumnMapper(name="입원  7일 SODIUM 검사결과 평균", category=LRPCategory.test),
    "d1_1_troponin": ColumnMapper(name="입원  1일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d1_2_troponin": ColumnMapper(name="입원  1일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d1_3_troponin": ColumnMapper(name="입원  1일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d2_1_troponin": ColumnMapper(name="입원  2일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d2_2_troponin": ColumnMapper(name="입원  2일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d2_3_troponin": ColumnMapper(name="입원  2일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d3_1_troponin": ColumnMapper(name="입원  3일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d3_2_troponin": ColumnMapper(name="입원  3일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d3_3_troponin": ColumnMapper(name="입원  3일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d4_1_troponin": ColumnMapper(name="입원  4일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d4_2_troponin": ColumnMapper(name="입원  4일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d4_3_troponin": ColumnMapper(name="입원  4일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d5_1_troponin": ColumnMapper(name="입원  5일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d5_2_troponin": ColumnMapper(name="입원  5일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d5_3_troponin": ColumnMapper(name="입원  5일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d6_1_troponin": ColumnMapper(name="입원  6일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d6_2_troponin": ColumnMapper(name="입원  6일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d6_3_troponin": ColumnMapper(name="입원  6일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d7_1_troponin": ColumnMapper(name="입원  7일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d7_2_troponin": ColumnMapper(name="입원  7일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d7_3_troponin": ColumnMapper(name="입원  7일 TROPONIN 검사결과 평균", category=LRPCategory.test),
    "d1_1_wbc": ColumnMapper(name="입원  1일 WBC 검사결과 평균", category=LRPCategory.test),
    "d1_2_wbc": ColumnMapper(name="입원  1일 WBC 검사결과 평균", category=LRPCategory.test),
    "d1_3_wbc": ColumnMapper(name="입원  1일 WBC 검사결과 평균", category=LRPCategory.test),
    "d2_1_wbc": ColumnMapper(name="입원  2일 WBC 검사결과 평균", category=LRPCategory.test),
    "d2_2_wbc": ColumnMapper(name="입원  2일 WBC 검사결과 평균", category=LRPCategory.test),
    "d2_3_wbc": ColumnMapper(name="입원  2일 WBC 검사결과 평균", category=LRPCategory.test),
    "d3_1_wbc": ColumnMapper(name="입원  3일 WBC 검사결과 평균", category=LRPCategory.test),
    "d3_2_wbc": ColumnMapper(name="입원  3일 WBC 검사결과 평균", category=LRPCategory.test),
    "d3_3_wbc": ColumnMapper(name="입원  3일 WBC 검사결과 평균", category=LRPCategory.test),
    "d4_1_wbc": ColumnMapper(name="입원  4일 WBC 검사결과 평균", category=LRPCategory.test),
    "d4_2_wbc": ColumnMapper(name="입원  4일 WBC 검사결과 평균", category=LRPCategory.test),
    "d4_3_wbc": ColumnMapper(name="입원  4일 WBC 검사결과 평균", category=LRPCategory.test),
    "d5_1_wbc": ColumnMapper(name="입원  5일 WBC 검사결과 평균", category=LRPCategory.test),
    "d5_2_wbc": ColumnMapper(name="입원  5일 WBC 검사결과 평균", category=LRPCategory.test),
    "d5_3_wbc": ColumnMapper(name="입원  5일 WBC 검사결과 평균", category=LRPCategory.test),
    "d6_1_wbc": ColumnMapper(name="입원  6일 WBC 검사결과 평균", category=LRPCategory.test),
    "d6_2_wbc": ColumnMapper(name="입원  6일 WBC 검사결과 평균", category=LRPCategory.test),
    "d6_3_wbc": ColumnMapper(name="입원  6일 WBC 검사결과 평균", category=LRPCategory.test),
    "d7_1_wbc": ColumnMapper(name="입원  7일 WBC 검사결과 평균", category=LRPCategory.test),
    "d7_2_wbc": ColumnMapper(name="입원  7일 WBC 검사결과 평균", category=LRPCategory.test),
    "d7_3_wbc": ColumnMapper(name="입원  7일 WBC 검사결과 평균", category=LRPCategory.test),
    "d1_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_1_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_2_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_3_sbp_max": ColumnMapper(name="SBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_1_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_2_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_3_dbp_max": ColumnMapper(name="DBP 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_1_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_2_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_3_pr_max": ColumnMapper(name="PR 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d2_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d3_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d4_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d5_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d6_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_1_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_2_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d7_3_bt_max": ColumnMapper(name="BT 측정결과 최대값", category=LRPCategory.vital_signs),
    "d1_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_1_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_2_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_3_sbp_avg": ColumnMapper(name="SBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_1_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_2_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_3_dbp_avg": ColumnMapper(name="DBP 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_1_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_2_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_3_pr_avg": ColumnMapper(name="PR 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d2_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d3_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d4_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d5_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d6_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_1_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_2_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d7_3_bt_avg": ColumnMapper(name="BT 측정결과 평균", category=LRPCategory.vital_signs),
    "d1_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_1_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_2_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_3_sbp_min": ColumnMapper(name="SBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_1_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_2_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_3_dbp_min": ColumnMapper(name="DBP 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_1_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_2_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_3_pr_min": ColumnMapper(name="PR 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d1_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d2_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d3_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d4_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d5_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d6_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_1_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_2_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "d7_3_bt_min": ColumnMapper(name="BT 측정결과 최소값", category=LRPCategory.vital_signs),
    "aki_nth_day": ColumnMapper(name="AKI 최초 발생 입원일(참고)", category=None),
    "d1_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d1_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d1_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d2_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d2_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d2_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d3_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d3_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d3_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d4_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d4_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d4_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d5_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d5_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d5_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d6_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d6_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d6_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d7_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d7_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d7_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d8_1_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d8_2_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d8_3_aki": ColumnMapper(name="AKI 발생 여부", category=None),
    "d1_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d1_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d1_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d2_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d2_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d2_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d3_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d3_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d3_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d4_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d4_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d4_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d5_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d5_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d5_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d6_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d6_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d6_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d7_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d7_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d7_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d8_1_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d8_2_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d8_3_aki_critical": ColumnMapper(name="CRITICAL AKI 발생 여부", category=None),
    "d1_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d2_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d3_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d4_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d5_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d6_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d7_dialysis": ColumnMapper(name="투석 여부", category=None),
    "d8_dialysis": ColumnMapper(name="투석 여부", category=None),
    "dialysis_in_100d": ColumnMapper(name="입원일부터 100일 이내 투석 여부", category=None),
    "death_in_100d": ColumnMapper(name="입원일부터 100일 이내 사망 여부", category=None),
    "ex_error_deathdate": ColumnMapper(name="제외 - 사망일자 오류", category=None),
    "esrd_in_100d": ColumnMapper(name="입원일부터 100일 이내 ESRD 진단 여부", category=None),
    "capd_in_100d": ColumnMapper(name="입원일부터 100일 이내 CAPD 여부", category=None),
    "avf_in_100d": ColumnMapper(name="입원일부터 100일 이내 AVF 여부", category=None),
    "cr_min_3w": ColumnMapper(name="입원일부터 1주 - 3주 이내 CR 최소값", category=None),
    "cr_min_5w": ColumnMapper(name="입원일부터 1주 - 5주 이내 CR 최소값", category=None),
    "cr_min_100d": ColumnMapper(name="입원일부터 100인 이내 CR 최소값", category=None),
    "ex_age": ColumnMapper(name="제외 - 나이 18세 미만", category=None),
    "ex_nobase": ColumnMapper(name="제외 - BASELINE CREATININE 없음", category=None),
    "ex_bcr4": ColumnMapper(name="제외 - BASELINE CREATININE 4 이상", category=None),
    "ex_begfr15": ColumnMapper(name="제외 - BASELINE EGFR 15 미만", category=None),
    "ex_nobmi": ColumnMapper(name="제외 - BMI 없음", category=None),
    "ex_nocr": ColumnMapper(name="제외 - 이내 CR 검사결과 없음", category=None),
    "ex_nolab": ColumnMapper(name="제외 - 검사결과 결측치 있는 경우", category=None),
    "ex_novital": ColumnMapper(name="제외 - VITAL 결측치 있는 경우", category=None),
    "ex_pre_dialysis": ColumnMapper(name="제외 - 입원 전 투석한 경우", category=None),
    "ex_pre_esrd": ColumnMapper(name="제외 - 입원 전 ESRD 진단 받은 경우", category=None),
    "ex_all": ColumnMapper(name="제외 - ex_age ~ ex_pre_esrd 최대값", category=None),
    "index_case": ColumnMapper(name="연건 ex_all = 0, ex_error_deathdate = 0 중 최초입원", category=None)
}


def get_record_column_key_and_formatted(column, day: Optional[int] = None) -> Tuple[str, str]:
    if re.compile('(^d\d_\d_)').search(column):
        col_day = day - int(column[1])
        formatted = f"d{col_day}{column[2:]}"
        return column[4:], formatted
    if re.compile('(^d_\d_)').search(column):
        col_day = day - int(column[2])
        formatted = f"d{col_day}{column[3:]}"
        return column[2:], formatted

    return column, column


def map_record_columns(day: int, record: List[Tuple[str, float]], limit: int = 10) -> Dict[str, dict]:
    res = {}

    for column, value in record:
        key, orig_col = get_record_column_key_and_formatted(
            column, day)

        if (key in res) or (orig_col not in column_mapping):
            continue

        res[key] = {
            "column": column,
            "original_column": orig_col,
            "value": value,
            "mapper": column_mapping[orig_col]
        }

        if len(res) == limit:
            break
    return res
